# Generated by Django 5.2.1 on 2025-05-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0004_department_alter_student_id_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
