# Generated by Django 5.2.1 on 2025-05-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student', #in student the changes happen
            name='email', #in student class the email the changes has been occured
            field=models.EmailField(max_length=254, unique=True), #the changes in email field
        ),
    ]
