# Generated by Django 5.2.1 on 2025-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='name',
            new_name='car_name',
        ),
        migrations.AlterField(
            model_name='cars',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
